/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'cpu_stage1' in SOPC Builder design 'MPSoC'
 * SOPC Builder design path: C:/Users/DELL/Documents/advanced_embedded_systems/practical_4/NIOS/MPSoC.sopcinfo
 *
 * Generated: Mon Mar 09 14:44:17 IST 2026
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_qsys"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x08040820
#define ALT_CPU_CPU_FREQ 50000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "tiny"
#define ALT_CPU_DATA_ADDR_WIDTH 0x1c
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EXCEPTION_ADDR 0x08020020
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 50000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 0
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 0
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_ICACHE_SIZE 0
#define ALT_CPU_INST_ADDR_WIDTH 0x1c
#define ALT_CPU_NAME "cpu_stage1"
#define ALT_CPU_RESET_ADDR 0x08020000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x08040820
#define NIOS2_CPU_FREQ 50000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "tiny"
#define NIOS2_DATA_ADDR_WIDTH 0x1c
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EXCEPTION_ADDR 0x08020020
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 0
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 0
#define NIOS2_ICACHE_LINE_SIZE_LOG2 0
#define NIOS2_ICACHE_SIZE 0
#define NIOS2_INST_ADDR_WIDTH 0x1c
#define NIOS2_RESET_ADDR 0x08020000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_FIFO
#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_NEW_SDRAM_CONTROLLER
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_SYSID_QSYS
#define __ALTERA_AVALON_TIMER
#define __ALTERA_NIOS2_QSYS


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone IV E"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart_1"
#define ALT_STDERR_BASE 0x80410e0
#define ALT_STDERR_DEV jtag_uart_1
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/jtag_uart_1"
#define ALT_STDIN_BASE 0x80410e0
#define ALT_STDIN_DEV jtag_uart_1
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/jtag_uart_1"
#define ALT_STDOUT_BASE 0x80410e0
#define ALT_STDOUT_DEV jtag_uart_1
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "MPSoC"


/*
 * altera_hostfs configuration
 *
 */

#define ALTERA_HOSTFS_NAME "/mnt/host"


/*
 * fifo_1to2_Cb_in configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_1to2_Cb_in altera_avalon_fifo
#define FIFO_1TO2_CB_IN_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_1TO2_CB_IN_AVALONMM_AVALONST_DATA_WIDTH 16
#define FIFO_1TO2_CB_IN_BASE 0x8041100
#define FIFO_1TO2_CB_IN_BITS_PER_SYMBOL 16
#define FIFO_1TO2_CB_IN_CHANNEL_WIDTH 8
#define FIFO_1TO2_CB_IN_ERROR_WIDTH 8
#define FIFO_1TO2_CB_IN_FIFO_DEPTH 64
#define FIFO_1TO2_CB_IN_IRQ -1
#define FIFO_1TO2_CB_IN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_1TO2_CB_IN_NAME "/dev/fifo_1to2_Cb_in"
#define FIFO_1TO2_CB_IN_SINGLE_CLOCK_MODE 0
#define FIFO_1TO2_CB_IN_SPAN 4
#define FIFO_1TO2_CB_IN_SYMBOLS_PER_BEAT 1
#define FIFO_1TO2_CB_IN_TYPE "altera_avalon_fifo"
#define FIFO_1TO2_CB_IN_USE_AVALONMM_READ_SLAVE 1
#define FIFO_1TO2_CB_IN_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_1TO2_CB_IN_USE_AVALONST_SINK 0
#define FIFO_1TO2_CB_IN_USE_AVALONST_SOURCE 0
#define FIFO_1TO2_CB_IN_USE_BACKPRESSURE 1
#define FIFO_1TO2_CB_IN_USE_IRQ 0
#define FIFO_1TO2_CB_IN_USE_PACKET 0
#define FIFO_1TO2_CB_IN_USE_READ_CONTROL 1
#define FIFO_1TO2_CB_IN_USE_REGISTER 0
#define FIFO_1TO2_CB_IN_USE_WRITE_CONTROL 1


/*
 * fifo_1to2_Cb_in_csr configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_1to2_Cb_in_csr altera_avalon_fifo
#define FIFO_1TO2_CB_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_1TO2_CB_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 16
#define FIFO_1TO2_CB_IN_CSR_BASE 0x8041080
#define FIFO_1TO2_CB_IN_CSR_BITS_PER_SYMBOL 16
#define FIFO_1TO2_CB_IN_CSR_CHANNEL_WIDTH 8
#define FIFO_1TO2_CB_IN_CSR_ERROR_WIDTH 8
#define FIFO_1TO2_CB_IN_CSR_FIFO_DEPTH 64
#define FIFO_1TO2_CB_IN_CSR_IRQ -1
#define FIFO_1TO2_CB_IN_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_1TO2_CB_IN_CSR_NAME "/dev/fifo_1to2_Cb_in_csr"
#define FIFO_1TO2_CB_IN_CSR_SINGLE_CLOCK_MODE 0
#define FIFO_1TO2_CB_IN_CSR_SPAN 32
#define FIFO_1TO2_CB_IN_CSR_SYMBOLS_PER_BEAT 1
#define FIFO_1TO2_CB_IN_CSR_TYPE "altera_avalon_fifo"
#define FIFO_1TO2_CB_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_1TO2_CB_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_1TO2_CB_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_1TO2_CB_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_1TO2_CB_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_1TO2_CB_IN_CSR_USE_IRQ 0
#define FIFO_1TO2_CB_IN_CSR_USE_PACKET 0
#define FIFO_1TO2_CB_IN_CSR_USE_READ_CONTROL 1
#define FIFO_1TO2_CB_IN_CSR_USE_REGISTER 0
#define FIFO_1TO2_CB_IN_CSR_USE_WRITE_CONTROL 1


/*
 * fifo_1to2_Cr_in configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_1to2_Cr_in altera_avalon_fifo
#define FIFO_1TO2_CR_IN_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_1TO2_CR_IN_AVALONMM_AVALONST_DATA_WIDTH 16
#define FIFO_1TO2_CR_IN_BASE 0x80410fc
#define FIFO_1TO2_CR_IN_BITS_PER_SYMBOL 16
#define FIFO_1TO2_CR_IN_CHANNEL_WIDTH 8
#define FIFO_1TO2_CR_IN_ERROR_WIDTH 8
#define FIFO_1TO2_CR_IN_FIFO_DEPTH 64
#define FIFO_1TO2_CR_IN_IRQ -1
#define FIFO_1TO2_CR_IN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_1TO2_CR_IN_NAME "/dev/fifo_1to2_Cr_in"
#define FIFO_1TO2_CR_IN_SINGLE_CLOCK_MODE 0
#define FIFO_1TO2_CR_IN_SPAN 4
#define FIFO_1TO2_CR_IN_SYMBOLS_PER_BEAT 1
#define FIFO_1TO2_CR_IN_TYPE "altera_avalon_fifo"
#define FIFO_1TO2_CR_IN_USE_AVALONMM_READ_SLAVE 1
#define FIFO_1TO2_CR_IN_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_1TO2_CR_IN_USE_AVALONST_SINK 0
#define FIFO_1TO2_CR_IN_USE_AVALONST_SOURCE 0
#define FIFO_1TO2_CR_IN_USE_BACKPRESSURE 1
#define FIFO_1TO2_CR_IN_USE_IRQ 0
#define FIFO_1TO2_CR_IN_USE_PACKET 0
#define FIFO_1TO2_CR_IN_USE_READ_CONTROL 1
#define FIFO_1TO2_CR_IN_USE_REGISTER 0
#define FIFO_1TO2_CR_IN_USE_WRITE_CONTROL 1


/*
 * fifo_1to2_Cr_in_csr configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_1to2_Cr_in_csr altera_avalon_fifo
#define FIFO_1TO2_CR_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_1TO2_CR_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 16
#define FIFO_1TO2_CR_IN_CSR_BASE 0x8041060
#define FIFO_1TO2_CR_IN_CSR_BITS_PER_SYMBOL 16
#define FIFO_1TO2_CR_IN_CSR_CHANNEL_WIDTH 8
#define FIFO_1TO2_CR_IN_CSR_ERROR_WIDTH 8
#define FIFO_1TO2_CR_IN_CSR_FIFO_DEPTH 64
#define FIFO_1TO2_CR_IN_CSR_IRQ -1
#define FIFO_1TO2_CR_IN_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_1TO2_CR_IN_CSR_NAME "/dev/fifo_1to2_Cr_in_csr"
#define FIFO_1TO2_CR_IN_CSR_SINGLE_CLOCK_MODE 0
#define FIFO_1TO2_CR_IN_CSR_SPAN 32
#define FIFO_1TO2_CR_IN_CSR_SYMBOLS_PER_BEAT 1
#define FIFO_1TO2_CR_IN_CSR_TYPE "altera_avalon_fifo"
#define FIFO_1TO2_CR_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_1TO2_CR_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_1TO2_CR_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_1TO2_CR_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_1TO2_CR_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_1TO2_CR_IN_CSR_USE_IRQ 0
#define FIFO_1TO2_CR_IN_CSR_USE_PACKET 0
#define FIFO_1TO2_CR_IN_CSR_USE_READ_CONTROL 1
#define FIFO_1TO2_CR_IN_CSR_USE_REGISTER 0
#define FIFO_1TO2_CR_IN_CSR_USE_WRITE_CONTROL 1


/*
 * fifo_1to2_Y_in configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_1to2_Y_in altera_avalon_fifo
#define FIFO_1TO2_Y_IN_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_1TO2_Y_IN_AVALONMM_AVALONST_DATA_WIDTH 16
#define FIFO_1TO2_Y_IN_BASE 0x8041104
#define FIFO_1TO2_Y_IN_BITS_PER_SYMBOL 16
#define FIFO_1TO2_Y_IN_CHANNEL_WIDTH 8
#define FIFO_1TO2_Y_IN_ERROR_WIDTH 8
#define FIFO_1TO2_Y_IN_FIFO_DEPTH 64
#define FIFO_1TO2_Y_IN_IRQ -1
#define FIFO_1TO2_Y_IN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_1TO2_Y_IN_NAME "/dev/fifo_1to2_Y_in"
#define FIFO_1TO2_Y_IN_SINGLE_CLOCK_MODE 0
#define FIFO_1TO2_Y_IN_SPAN 4
#define FIFO_1TO2_Y_IN_SYMBOLS_PER_BEAT 1
#define FIFO_1TO2_Y_IN_TYPE "altera_avalon_fifo"
#define FIFO_1TO2_Y_IN_USE_AVALONMM_READ_SLAVE 1
#define FIFO_1TO2_Y_IN_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_1TO2_Y_IN_USE_AVALONST_SINK 0
#define FIFO_1TO2_Y_IN_USE_AVALONST_SOURCE 0
#define FIFO_1TO2_Y_IN_USE_BACKPRESSURE 1
#define FIFO_1TO2_Y_IN_USE_IRQ 0
#define FIFO_1TO2_Y_IN_USE_PACKET 0
#define FIFO_1TO2_Y_IN_USE_READ_CONTROL 1
#define FIFO_1TO2_Y_IN_USE_REGISTER 0
#define FIFO_1TO2_Y_IN_USE_WRITE_CONTROL 1


/*
 * fifo_1to2_Y_in_csr configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_1to2_Y_in_csr altera_avalon_fifo
#define FIFO_1TO2_Y_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_1TO2_Y_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 16
#define FIFO_1TO2_Y_IN_CSR_BASE 0x80410a0
#define FIFO_1TO2_Y_IN_CSR_BITS_PER_SYMBOL 16
#define FIFO_1TO2_Y_IN_CSR_CHANNEL_WIDTH 8
#define FIFO_1TO2_Y_IN_CSR_ERROR_WIDTH 8
#define FIFO_1TO2_Y_IN_CSR_FIFO_DEPTH 64
#define FIFO_1TO2_Y_IN_CSR_IRQ -1
#define FIFO_1TO2_Y_IN_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_1TO2_Y_IN_CSR_NAME "/dev/fifo_1to2_Y_in_csr"
#define FIFO_1TO2_Y_IN_CSR_SINGLE_CLOCK_MODE 0
#define FIFO_1TO2_Y_IN_CSR_SPAN 32
#define FIFO_1TO2_Y_IN_CSR_SYMBOLS_PER_BEAT 1
#define FIFO_1TO2_Y_IN_CSR_TYPE "altera_avalon_fifo"
#define FIFO_1TO2_Y_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_1TO2_Y_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_1TO2_Y_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_1TO2_Y_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_1TO2_Y_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_1TO2_Y_IN_CSR_USE_IRQ 0
#define FIFO_1TO2_Y_IN_CSR_USE_PACKET 0
#define FIFO_1TO2_Y_IN_CSR_USE_READ_CONTROL 1
#define FIFO_1TO2_Y_IN_CSR_USE_REGISTER 0
#define FIFO_1TO2_Y_IN_CSR_USE_WRITE_CONTROL 1


/*
 * fifo_1to4_param_in configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_1to4_param_in altera_avalon_fifo
#define FIFO_1TO4_PARAM_IN_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_1TO4_PARAM_IN_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_1TO4_PARAM_IN_BASE 0x80410f8
#define FIFO_1TO4_PARAM_IN_BITS_PER_SYMBOL 32
#define FIFO_1TO4_PARAM_IN_CHANNEL_WIDTH 8
#define FIFO_1TO4_PARAM_IN_ERROR_WIDTH 8
#define FIFO_1TO4_PARAM_IN_FIFO_DEPTH 8
#define FIFO_1TO4_PARAM_IN_IRQ -1
#define FIFO_1TO4_PARAM_IN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_1TO4_PARAM_IN_NAME "/dev/fifo_1to4_param_in"
#define FIFO_1TO4_PARAM_IN_SINGLE_CLOCK_MODE 0
#define FIFO_1TO4_PARAM_IN_SPAN 4
#define FIFO_1TO4_PARAM_IN_SYMBOLS_PER_BEAT 1
#define FIFO_1TO4_PARAM_IN_TYPE "altera_avalon_fifo"
#define FIFO_1TO4_PARAM_IN_USE_AVALONMM_READ_SLAVE 1
#define FIFO_1TO4_PARAM_IN_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_1TO4_PARAM_IN_USE_AVALONST_SINK 0
#define FIFO_1TO4_PARAM_IN_USE_AVALONST_SOURCE 0
#define FIFO_1TO4_PARAM_IN_USE_BACKPRESSURE 1
#define FIFO_1TO4_PARAM_IN_USE_IRQ 0
#define FIFO_1TO4_PARAM_IN_USE_PACKET 0
#define FIFO_1TO4_PARAM_IN_USE_READ_CONTROL 1
#define FIFO_1TO4_PARAM_IN_USE_REGISTER 0
#define FIFO_1TO4_PARAM_IN_USE_WRITE_CONTROL 1


/*
 * fifo_1to4_param_in_csr configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_1to4_param_in_csr altera_avalon_fifo
#define FIFO_1TO4_PARAM_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_1TO4_PARAM_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_1TO4_PARAM_IN_CSR_BASE 0x8041040
#define FIFO_1TO4_PARAM_IN_CSR_BITS_PER_SYMBOL 32
#define FIFO_1TO4_PARAM_IN_CSR_CHANNEL_WIDTH 8
#define FIFO_1TO4_PARAM_IN_CSR_ERROR_WIDTH 8
#define FIFO_1TO4_PARAM_IN_CSR_FIFO_DEPTH 8
#define FIFO_1TO4_PARAM_IN_CSR_IRQ -1
#define FIFO_1TO4_PARAM_IN_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_1TO4_PARAM_IN_CSR_NAME "/dev/fifo_1to4_param_in_csr"
#define FIFO_1TO4_PARAM_IN_CSR_SINGLE_CLOCK_MODE 0
#define FIFO_1TO4_PARAM_IN_CSR_SPAN 32
#define FIFO_1TO4_PARAM_IN_CSR_SYMBOLS_PER_BEAT 1
#define FIFO_1TO4_PARAM_IN_CSR_TYPE "altera_avalon_fifo"
#define FIFO_1TO4_PARAM_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_1TO4_PARAM_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_1TO4_PARAM_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_1TO4_PARAM_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_1TO4_PARAM_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_1TO4_PARAM_IN_CSR_USE_IRQ 0
#define FIFO_1TO4_PARAM_IN_CSR_USE_PACKET 0
#define FIFO_1TO4_PARAM_IN_CSR_USE_READ_CONTROL 1
#define FIFO_1TO4_PARAM_IN_CSR_USE_REGISTER 0
#define FIFO_1TO4_PARAM_IN_CSR_USE_WRITE_CONTROL 1


/*
 * fifo_1to5_param_in configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_1to5_param_in altera_avalon_fifo
#define FIFO_1TO5_PARAM_IN_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_1TO5_PARAM_IN_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_1TO5_PARAM_IN_BASE 0x80410f4
#define FIFO_1TO5_PARAM_IN_BITS_PER_SYMBOL 32
#define FIFO_1TO5_PARAM_IN_CHANNEL_WIDTH 8
#define FIFO_1TO5_PARAM_IN_ERROR_WIDTH 8
#define FIFO_1TO5_PARAM_IN_FIFO_DEPTH 8
#define FIFO_1TO5_PARAM_IN_IRQ -1
#define FIFO_1TO5_PARAM_IN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_1TO5_PARAM_IN_NAME "/dev/fifo_1to5_param_in"
#define FIFO_1TO5_PARAM_IN_SINGLE_CLOCK_MODE 0
#define FIFO_1TO5_PARAM_IN_SPAN 4
#define FIFO_1TO5_PARAM_IN_SYMBOLS_PER_BEAT 1
#define FIFO_1TO5_PARAM_IN_TYPE "altera_avalon_fifo"
#define FIFO_1TO5_PARAM_IN_USE_AVALONMM_READ_SLAVE 1
#define FIFO_1TO5_PARAM_IN_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_1TO5_PARAM_IN_USE_AVALONST_SINK 0
#define FIFO_1TO5_PARAM_IN_USE_AVALONST_SOURCE 0
#define FIFO_1TO5_PARAM_IN_USE_BACKPRESSURE 1
#define FIFO_1TO5_PARAM_IN_USE_IRQ 0
#define FIFO_1TO5_PARAM_IN_USE_PACKET 0
#define FIFO_1TO5_PARAM_IN_USE_READ_CONTROL 1
#define FIFO_1TO5_PARAM_IN_USE_REGISTER 0
#define FIFO_1TO5_PARAM_IN_USE_WRITE_CONTROL 1


/*
 * fifo_1to5_param_in_csr configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_1to5_param_in_csr altera_avalon_fifo
#define FIFO_1TO5_PARAM_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_1TO5_PARAM_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_1TO5_PARAM_IN_CSR_BASE 0x8041020
#define FIFO_1TO5_PARAM_IN_CSR_BITS_PER_SYMBOL 32
#define FIFO_1TO5_PARAM_IN_CSR_CHANNEL_WIDTH 8
#define FIFO_1TO5_PARAM_IN_CSR_ERROR_WIDTH 8
#define FIFO_1TO5_PARAM_IN_CSR_FIFO_DEPTH 8
#define FIFO_1TO5_PARAM_IN_CSR_IRQ -1
#define FIFO_1TO5_PARAM_IN_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_1TO5_PARAM_IN_CSR_NAME "/dev/fifo_1to5_param_in_csr"
#define FIFO_1TO5_PARAM_IN_CSR_SINGLE_CLOCK_MODE 0
#define FIFO_1TO5_PARAM_IN_CSR_SPAN 32
#define FIFO_1TO5_PARAM_IN_CSR_SYMBOLS_PER_BEAT 1
#define FIFO_1TO5_PARAM_IN_CSR_TYPE "altera_avalon_fifo"
#define FIFO_1TO5_PARAM_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_1TO5_PARAM_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_1TO5_PARAM_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_1TO5_PARAM_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_1TO5_PARAM_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_1TO5_PARAM_IN_CSR_USE_IRQ 0
#define FIFO_1TO5_PARAM_IN_CSR_USE_PACKET 0
#define FIFO_1TO5_PARAM_IN_CSR_USE_READ_CONTROL 1
#define FIFO_1TO5_PARAM_IN_CSR_USE_REGISTER 0
#define FIFO_1TO5_PARAM_IN_CSR_USE_WRITE_CONTROL 1


/*
 * fifo_1to6_fname_in configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_1to6_fname_in altera_avalon_fifo
#define FIFO_1TO6_FNAME_IN_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_1TO6_FNAME_IN_AVALONMM_AVALONST_DATA_WIDTH 8
#define FIFO_1TO6_FNAME_IN_BASE 0x80410f0
#define FIFO_1TO6_FNAME_IN_BITS_PER_SYMBOL 8
#define FIFO_1TO6_FNAME_IN_CHANNEL_WIDTH 8
#define FIFO_1TO6_FNAME_IN_ERROR_WIDTH 8
#define FIFO_1TO6_FNAME_IN_FIFO_DEPTH 128
#define FIFO_1TO6_FNAME_IN_IRQ -1
#define FIFO_1TO6_FNAME_IN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_1TO6_FNAME_IN_NAME "/dev/fifo_1to6_fname_in"
#define FIFO_1TO6_FNAME_IN_SINGLE_CLOCK_MODE 0
#define FIFO_1TO6_FNAME_IN_SPAN 4
#define FIFO_1TO6_FNAME_IN_SYMBOLS_PER_BEAT 1
#define FIFO_1TO6_FNAME_IN_TYPE "altera_avalon_fifo"
#define FIFO_1TO6_FNAME_IN_USE_AVALONMM_READ_SLAVE 1
#define FIFO_1TO6_FNAME_IN_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_1TO6_FNAME_IN_USE_AVALONST_SINK 0
#define FIFO_1TO6_FNAME_IN_USE_AVALONST_SOURCE 0
#define FIFO_1TO6_FNAME_IN_USE_BACKPRESSURE 1
#define FIFO_1TO6_FNAME_IN_USE_IRQ 0
#define FIFO_1TO6_FNAME_IN_USE_PACKET 0
#define FIFO_1TO6_FNAME_IN_USE_READ_CONTROL 1
#define FIFO_1TO6_FNAME_IN_USE_REGISTER 0
#define FIFO_1TO6_FNAME_IN_USE_WRITE_CONTROL 1


/*
 * fifo_1to6_fname_in_csr configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_1to6_fname_in_csr altera_avalon_fifo
#define FIFO_1TO6_FNAME_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_1TO6_FNAME_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 8
#define FIFO_1TO6_FNAME_IN_CSR_BASE 0x8041000
#define FIFO_1TO6_FNAME_IN_CSR_BITS_PER_SYMBOL 8
#define FIFO_1TO6_FNAME_IN_CSR_CHANNEL_WIDTH 8
#define FIFO_1TO6_FNAME_IN_CSR_ERROR_WIDTH 8
#define FIFO_1TO6_FNAME_IN_CSR_FIFO_DEPTH 128
#define FIFO_1TO6_FNAME_IN_CSR_IRQ -1
#define FIFO_1TO6_FNAME_IN_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_1TO6_FNAME_IN_CSR_NAME "/dev/fifo_1to6_fname_in_csr"
#define FIFO_1TO6_FNAME_IN_CSR_SINGLE_CLOCK_MODE 0
#define FIFO_1TO6_FNAME_IN_CSR_SPAN 32
#define FIFO_1TO6_FNAME_IN_CSR_SYMBOLS_PER_BEAT 1
#define FIFO_1TO6_FNAME_IN_CSR_TYPE "altera_avalon_fifo"
#define FIFO_1TO6_FNAME_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_1TO6_FNAME_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define FIFO_1TO6_FNAME_IN_CSR_USE_AVALONST_SINK 0
#define FIFO_1TO6_FNAME_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_1TO6_FNAME_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_1TO6_FNAME_IN_CSR_USE_IRQ 0
#define FIFO_1TO6_FNAME_IN_CSR_USE_PACKET 0
#define FIFO_1TO6_FNAME_IN_CSR_USE_READ_CONTROL 1
#define FIFO_1TO6_FNAME_IN_CSR_USE_REGISTER 0
#define FIFO_1TO6_FNAME_IN_CSR_USE_WRITE_CONTROL 1


/*
 * hal configuration
 *
 */

#define ALT_MAX_FD 32
#define ALT_SYS_CLK TIMER_1
#define ALT_TIMESTAMP_CLK TIMER_1


/*
 * jtag_uart_1 configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart_1 altera_avalon_jtag_uart
#define JTAG_UART_1_BASE 0x80410e0
#define JTAG_UART_1_IRQ 0
#define JTAG_UART_1_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_1_NAME "/dev/jtag_uart_1"
#define JTAG_UART_1_READ_DEPTH 64
#define JTAG_UART_1_READ_THRESHOLD 8
#define JTAG_UART_1_SPAN 8
#define JTAG_UART_1_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_1_WRITE_DEPTH 64
#define JTAG_UART_1_WRITE_THRESHOLD 8


/*
 * ram_stage1 configuration
 *
 */

#define ALT_MODULE_CLASS_ram_stage1 altera_avalon_onchip_memory2
#define RAM_STAGE1_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define RAM_STAGE1_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define RAM_STAGE1_BASE 0x8020000
#define RAM_STAGE1_CONTENTS_INFO ""
#define RAM_STAGE1_DUAL_PORT 0
#define RAM_STAGE1_GUI_RAM_BLOCK_TYPE "AUTO"
#define RAM_STAGE1_INIT_CONTENTS_FILE "MPSoC_ram_stage1"
#define RAM_STAGE1_INIT_MEM_CONTENT 1
#define RAM_STAGE1_INSTANCE_ID "NONE"
#define RAM_STAGE1_IRQ -1
#define RAM_STAGE1_IRQ_INTERRUPT_CONTROLLER_ID -1
#define RAM_STAGE1_NAME "/dev/ram_stage1"
#define RAM_STAGE1_NON_DEFAULT_INIT_FILE_ENABLED 0
#define RAM_STAGE1_RAM_BLOCK_TYPE "AUTO"
#define RAM_STAGE1_READ_DURING_WRITE_MODE "DONT_CARE"
#define RAM_STAGE1_SINGLE_CLOCK_OP 0
#define RAM_STAGE1_SIZE_MULTIPLE 1
#define RAM_STAGE1_SIZE_VALUE 96000
#define RAM_STAGE1_SPAN 96000
#define RAM_STAGE1_TYPE "altera_avalon_onchip_memory2"
#define RAM_STAGE1_WRITABLE 1


/*
 * sdram_controller_stage1 configuration
 *
 */

#define ALT_MODULE_CLASS_sdram_controller_stage1 altera_avalon_new_sdram_controller
#define SDRAM_CONTROLLER_STAGE1_BASE 0x0
#define SDRAM_CONTROLLER_STAGE1_CAS_LATENCY 3
#define SDRAM_CONTROLLER_STAGE1_CONTENTS_INFO
#define SDRAM_CONTROLLER_STAGE1_INIT_NOP_DELAY 0.0
#define SDRAM_CONTROLLER_STAGE1_INIT_REFRESH_COMMANDS 2
#define SDRAM_CONTROLLER_STAGE1_IRQ -1
#define SDRAM_CONTROLLER_STAGE1_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SDRAM_CONTROLLER_STAGE1_IS_INITIALIZED 1
#define SDRAM_CONTROLLER_STAGE1_NAME "/dev/sdram_controller_stage1"
#define SDRAM_CONTROLLER_STAGE1_POWERUP_DELAY 100.0
#define SDRAM_CONTROLLER_STAGE1_REFRESH_PERIOD 15.625
#define SDRAM_CONTROLLER_STAGE1_REGISTER_DATA_IN 1
#define SDRAM_CONTROLLER_STAGE1_SDRAM_ADDR_WIDTH 0x19
#define SDRAM_CONTROLLER_STAGE1_SDRAM_BANK_WIDTH 2
#define SDRAM_CONTROLLER_STAGE1_SDRAM_COL_WIDTH 10
#define SDRAM_CONTROLLER_STAGE1_SDRAM_DATA_WIDTH 32
#define SDRAM_CONTROLLER_STAGE1_SDRAM_NUM_BANKS 4
#define SDRAM_CONTROLLER_STAGE1_SDRAM_NUM_CHIPSELECTS 1
#define SDRAM_CONTROLLER_STAGE1_SDRAM_ROW_WIDTH 13
#define SDRAM_CONTROLLER_STAGE1_SHARED_DATA 0
#define SDRAM_CONTROLLER_STAGE1_SIM_MODEL_BASE 0
#define SDRAM_CONTROLLER_STAGE1_SPAN 134217728
#define SDRAM_CONTROLLER_STAGE1_STARVATION_INDICATOR 0
#define SDRAM_CONTROLLER_STAGE1_TRISTATE_BRIDGE_SLAVE ""
#define SDRAM_CONTROLLER_STAGE1_TYPE "altera_avalon_new_sdram_controller"
#define SDRAM_CONTROLLER_STAGE1_T_AC 6.0
#define SDRAM_CONTROLLER_STAGE1_T_MRD 3
#define SDRAM_CONTROLLER_STAGE1_T_RCD 20.0
#define SDRAM_CONTROLLER_STAGE1_T_RFC 70.0
#define SDRAM_CONTROLLER_STAGE1_T_RP 20.0
#define SDRAM_CONTROLLER_STAGE1_T_WR 14.0


/*
 * sysid_qsys_0 configuration
 *
 */

#define ALT_MODULE_CLASS_sysid_qsys_0 altera_avalon_sysid_qsys
#define SYSID_QSYS_0_BASE 0x80410e8
#define SYSID_QSYS_0_ID 0
#define SYSID_QSYS_0_IRQ -1
#define SYSID_QSYS_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYSID_QSYS_0_NAME "/dev/sysid_qsys_0"
#define SYSID_QSYS_0_SPAN 8
#define SYSID_QSYS_0_TIMESTAMP 1773046779
#define SYSID_QSYS_0_TYPE "altera_avalon_sysid_qsys"


/*
 * timer_1 configuration
 *
 */

#define ALT_MODULE_CLASS_timer_1 altera_avalon_timer
#define TIMER_1_ALWAYS_RUN 0
#define TIMER_1_BASE 0x80410c0
#define TIMER_1_COUNTER_SIZE 32
#define TIMER_1_FIXED_PERIOD 0
#define TIMER_1_FREQ 50000000
#define TIMER_1_IRQ 1
#define TIMER_1_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TIMER_1_LOAD_VALUE 49999
#define TIMER_1_MULT 0.0010
#define TIMER_1_NAME "/dev/timer_1"
#define TIMER_1_PERIOD 1
#define TIMER_1_PERIOD_UNITS "ms"
#define TIMER_1_RESET_OUTPUT 0
#define TIMER_1_SNAPSHOT 1
#define TIMER_1_SPAN 32
#define TIMER_1_TICKS_PER_SEC 1000.0
#define TIMER_1_TIMEOUT_PULSE_OUTPUT 0
#define TIMER_1_TYPE "altera_avalon_timer"

#endif /* __SYSTEM_H_ */
