// SoC.v

// Generated using ACDS version 13.1 162 at 2025.11.26.14:47:33

`timescale 1 ps / 1 ps
module SoC (
		input  wire        clk_clk,           //         clk.clk
		input  wire        reset_reset_n,     //       reset.reset_n
		output wire [7:0]  leds_export,       //        leds.export
		output wire [12:0] sdram_wires_addr,  // sdram_wires.addr
		output wire [1:0]  sdram_wires_ba,    //            .ba
		output wire        sdram_wires_cas_n, //            .cas_n
		output wire        sdram_wires_cke,   //            .cke
		output wire        sdram_wires_cs_n,  //            .cs_n
		inout  wire [31:0] sdram_wires_dq,    //            .dq
		output wire [3:0]  sdram_wires_dqm,   //            .dqm
		output wire        sdram_wires_ras_n, //            .ras_n
		output wire        sdram_wires_we_n,  //            .we_n
		output wire        c2_clock_clk       //    c2_clock.clk
	);

	wire         altpll_c0_clk;                                                   // altpll:c0 -> [cpu:clk, irq_mapper:clk, irq_synchronizer:sender_clk, jtag_uart:clk, master_clock_crossing_bridge:s0_clk, mm_interconnect_0:altpll_c0_clk, pio:clk, rst_controller:clk, sdram:clk]
	wire         altpll_c1_clk;                                                   // altpll:c1 -> [irq_synchronizer:receiver_clk, master_clock_crossing_bridge:m0_clk, mm_interconnect_1:altpll_c1_clk, rst_controller_001:clk, sysid_qsys_0:clock, timer:clk]
	wire         mm_interconnect_0_master_clock_crossing_bridge_s0_waitrequest;   // master_clock_crossing_bridge:s0_waitrequest -> mm_interconnect_0:master_clock_crossing_bridge_s0_waitrequest
	wire   [0:0] mm_interconnect_0_master_clock_crossing_bridge_s0_burstcount;    // mm_interconnect_0:master_clock_crossing_bridge_s0_burstcount -> master_clock_crossing_bridge:s0_burstcount
	wire  [31:0] mm_interconnect_0_master_clock_crossing_bridge_s0_writedata;     // mm_interconnect_0:master_clock_crossing_bridge_s0_writedata -> master_clock_crossing_bridge:s0_writedata
	wire   [9:0] mm_interconnect_0_master_clock_crossing_bridge_s0_address;       // mm_interconnect_0:master_clock_crossing_bridge_s0_address -> master_clock_crossing_bridge:s0_address
	wire         mm_interconnect_0_master_clock_crossing_bridge_s0_write;         // mm_interconnect_0:master_clock_crossing_bridge_s0_write -> master_clock_crossing_bridge:s0_write
	wire         mm_interconnect_0_master_clock_crossing_bridge_s0_read;          // mm_interconnect_0:master_clock_crossing_bridge_s0_read -> master_clock_crossing_bridge:s0_read
	wire  [31:0] mm_interconnect_0_master_clock_crossing_bridge_s0_readdata;      // master_clock_crossing_bridge:s0_readdata -> mm_interconnect_0:master_clock_crossing_bridge_s0_readdata
	wire         mm_interconnect_0_master_clock_crossing_bridge_s0_debugaccess;   // mm_interconnect_0:master_clock_crossing_bridge_s0_debugaccess -> master_clock_crossing_bridge:s0_debugaccess
	wire         mm_interconnect_0_master_clock_crossing_bridge_s0_readdatavalid; // master_clock_crossing_bridge:s0_readdatavalid -> mm_interconnect_0:master_clock_crossing_bridge_s0_readdatavalid
	wire   [3:0] mm_interconnect_0_master_clock_crossing_bridge_s0_byteenable;    // mm_interconnect_0:master_clock_crossing_bridge_s0_byteenable -> master_clock_crossing_bridge:s0_byteenable
	wire  [31:0] mm_interconnect_0_altpll_pll_slave_writedata;                    // mm_interconnect_0:altpll_pll_slave_writedata -> altpll:writedata
	wire   [1:0] mm_interconnect_0_altpll_pll_slave_address;                      // mm_interconnect_0:altpll_pll_slave_address -> altpll:address
	wire         mm_interconnect_0_altpll_pll_slave_write;                        // mm_interconnect_0:altpll_pll_slave_write -> altpll:write
	wire         mm_interconnect_0_altpll_pll_slave_read;                         // mm_interconnect_0:altpll_pll_slave_read -> altpll:read
	wire  [31:0] mm_interconnect_0_altpll_pll_slave_readdata;                     // altpll:readdata -> mm_interconnect_0:altpll_pll_slave_readdata
	wire         mm_interconnect_0_sdram_s1_waitrequest;                          // sdram:za_waitrequest -> mm_interconnect_0:sdram_s1_waitrequest
	wire  [31:0] mm_interconnect_0_sdram_s1_writedata;                            // mm_interconnect_0:sdram_s1_writedata -> sdram:az_data
	wire  [24:0] mm_interconnect_0_sdram_s1_address;                              // mm_interconnect_0:sdram_s1_address -> sdram:az_addr
	wire         mm_interconnect_0_sdram_s1_chipselect;                           // mm_interconnect_0:sdram_s1_chipselect -> sdram:az_cs
	wire         mm_interconnect_0_sdram_s1_write;                                // mm_interconnect_0:sdram_s1_write -> sdram:az_wr_n
	wire         mm_interconnect_0_sdram_s1_read;                                 // mm_interconnect_0:sdram_s1_read -> sdram:az_rd_n
	wire  [31:0] mm_interconnect_0_sdram_s1_readdata;                             // sdram:za_data -> mm_interconnect_0:sdram_s1_readdata
	wire         mm_interconnect_0_sdram_s1_readdatavalid;                        // sdram:za_valid -> mm_interconnect_0:sdram_s1_readdatavalid
	wire   [3:0] mm_interconnect_0_sdram_s1_byteenable;                           // mm_interconnect_0:sdram_s1_byteenable -> sdram:az_be_n
	wire         cpu_instruction_master_waitrequest;                              // mm_interconnect_0:cpu_instruction_master_waitrequest -> cpu:i_waitrequest
	wire  [28:0] cpu_instruction_master_address;                                  // cpu:i_address -> mm_interconnect_0:cpu_instruction_master_address
	wire         cpu_instruction_master_read;                                     // cpu:i_read -> mm_interconnect_0:cpu_instruction_master_read
	wire  [31:0] cpu_instruction_master_readdata;                                 // mm_interconnect_0:cpu_instruction_master_readdata -> cpu:i_readdata
	wire         cpu_data_master_waitrequest;                                     // mm_interconnect_0:cpu_data_master_waitrequest -> cpu:d_waitrequest
	wire  [31:0] cpu_data_master_writedata;                                       // cpu:d_writedata -> mm_interconnect_0:cpu_data_master_writedata
	wire  [28:0] cpu_data_master_address;                                         // cpu:d_address -> mm_interconnect_0:cpu_data_master_address
	wire         cpu_data_master_write;                                           // cpu:d_write -> mm_interconnect_0:cpu_data_master_write
	wire         cpu_data_master_read;                                            // cpu:d_read -> mm_interconnect_0:cpu_data_master_read
	wire  [31:0] cpu_data_master_readdata;                                        // mm_interconnect_0:cpu_data_master_readdata -> cpu:d_readdata
	wire         cpu_data_master_debugaccess;                                     // cpu:jtag_debug_module_debugaccess_to_roms -> mm_interconnect_0:cpu_data_master_debugaccess
	wire   [3:0] cpu_data_master_byteenable;                                      // cpu:d_byteenable -> mm_interconnect_0:cpu_data_master_byteenable
	wire  [31:0] mm_interconnect_0_pio_s1_writedata;                              // mm_interconnect_0:pio_s1_writedata -> pio:writedata
	wire   [1:0] mm_interconnect_0_pio_s1_address;                                // mm_interconnect_0:pio_s1_address -> pio:address
	wire         mm_interconnect_0_pio_s1_chipselect;                             // mm_interconnect_0:pio_s1_chipselect -> pio:chipselect
	wire         mm_interconnect_0_pio_s1_write;                                  // mm_interconnect_0:pio_s1_write -> pio:write_n
	wire  [31:0] mm_interconnect_0_pio_s1_readdata;                               // pio:readdata -> mm_interconnect_0:pio_s1_readdata
	wire         mm_interconnect_0_cpu_jtag_debug_module_waitrequest;             // cpu:jtag_debug_module_waitrequest -> mm_interconnect_0:cpu_jtag_debug_module_waitrequest
	wire  [31:0] mm_interconnect_0_cpu_jtag_debug_module_writedata;               // mm_interconnect_0:cpu_jtag_debug_module_writedata -> cpu:jtag_debug_module_writedata
	wire   [8:0] mm_interconnect_0_cpu_jtag_debug_module_address;                 // mm_interconnect_0:cpu_jtag_debug_module_address -> cpu:jtag_debug_module_address
	wire         mm_interconnect_0_cpu_jtag_debug_module_write;                   // mm_interconnect_0:cpu_jtag_debug_module_write -> cpu:jtag_debug_module_write
	wire         mm_interconnect_0_cpu_jtag_debug_module_read;                    // mm_interconnect_0:cpu_jtag_debug_module_read -> cpu:jtag_debug_module_read
	wire  [31:0] mm_interconnect_0_cpu_jtag_debug_module_readdata;                // cpu:jtag_debug_module_readdata -> mm_interconnect_0:cpu_jtag_debug_module_readdata
	wire         mm_interconnect_0_cpu_jtag_debug_module_debugaccess;             // mm_interconnect_0:cpu_jtag_debug_module_debugaccess -> cpu:jtag_debug_module_debugaccess
	wire   [3:0] mm_interconnect_0_cpu_jtag_debug_module_byteenable;              // mm_interconnect_0:cpu_jtag_debug_module_byteenable -> cpu:jtag_debug_module_byteenable
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest;       // jtag_uart:av_waitrequest -> mm_interconnect_0:jtag_uart_avalon_jtag_slave_waitrequest
	wire  [31:0] mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata;         // mm_interconnect_0:jtag_uart_avalon_jtag_slave_writedata -> jtag_uart:av_writedata
	wire   [0:0] mm_interconnect_0_jtag_uart_avalon_jtag_slave_address;           // mm_interconnect_0:jtag_uart_avalon_jtag_slave_address -> jtag_uart:av_address
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect;        // mm_interconnect_0:jtag_uart_avalon_jtag_slave_chipselect -> jtag_uart:av_chipselect
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_write;             // mm_interconnect_0:jtag_uart_avalon_jtag_slave_write -> jtag_uart:av_write_n
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_read;              // mm_interconnect_0:jtag_uart_avalon_jtag_slave_read -> jtag_uart:av_read_n
	wire  [31:0] mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata;          // jtag_uart:av_readdata -> mm_interconnect_0:jtag_uart_avalon_jtag_slave_readdata
	wire   [0:0] master_clock_crossing_bridge_m0_burstcount;                      // master_clock_crossing_bridge:m0_burstcount -> mm_interconnect_1:master_clock_crossing_bridge_m0_burstcount
	wire         master_clock_crossing_bridge_m0_waitrequest;                     // mm_interconnect_1:master_clock_crossing_bridge_m0_waitrequest -> master_clock_crossing_bridge:m0_waitrequest
	wire   [9:0] master_clock_crossing_bridge_m0_address;                         // master_clock_crossing_bridge:m0_address -> mm_interconnect_1:master_clock_crossing_bridge_m0_address
	wire  [31:0] master_clock_crossing_bridge_m0_writedata;                       // master_clock_crossing_bridge:m0_writedata -> mm_interconnect_1:master_clock_crossing_bridge_m0_writedata
	wire         master_clock_crossing_bridge_m0_write;                           // master_clock_crossing_bridge:m0_write -> mm_interconnect_1:master_clock_crossing_bridge_m0_write
	wire         master_clock_crossing_bridge_m0_read;                            // master_clock_crossing_bridge:m0_read -> mm_interconnect_1:master_clock_crossing_bridge_m0_read
	wire  [31:0] master_clock_crossing_bridge_m0_readdata;                        // mm_interconnect_1:master_clock_crossing_bridge_m0_readdata -> master_clock_crossing_bridge:m0_readdata
	wire         master_clock_crossing_bridge_m0_debugaccess;                     // master_clock_crossing_bridge:m0_debugaccess -> mm_interconnect_1:master_clock_crossing_bridge_m0_debugaccess
	wire   [3:0] master_clock_crossing_bridge_m0_byteenable;                      // master_clock_crossing_bridge:m0_byteenable -> mm_interconnect_1:master_clock_crossing_bridge_m0_byteenable
	wire         master_clock_crossing_bridge_m0_readdatavalid;                   // mm_interconnect_1:master_clock_crossing_bridge_m0_readdatavalid -> master_clock_crossing_bridge:m0_readdatavalid
	wire  [15:0] mm_interconnect_1_timer_s1_writedata;                            // mm_interconnect_1:timer_s1_writedata -> timer:writedata
	wire   [2:0] mm_interconnect_1_timer_s1_address;                              // mm_interconnect_1:timer_s1_address -> timer:address
	wire         mm_interconnect_1_timer_s1_chipselect;                           // mm_interconnect_1:timer_s1_chipselect -> timer:chipselect
	wire         mm_interconnect_1_timer_s1_write;                                // mm_interconnect_1:timer_s1_write -> timer:write_n
	wire  [15:0] mm_interconnect_1_timer_s1_readdata;                             // timer:readdata -> mm_interconnect_1:timer_s1_readdata
	wire   [0:0] mm_interconnect_1_sysid_qsys_0_control_slave_address;            // mm_interconnect_1:sysid_qsys_0_control_slave_address -> sysid_qsys_0:address
	wire  [31:0] mm_interconnect_1_sysid_qsys_0_control_slave_readdata;           // sysid_qsys_0:readdata -> mm_interconnect_1:sysid_qsys_0_control_slave_readdata
	wire         irq_mapper_receiver1_irq;                                        // jtag_uart:av_irq -> irq_mapper:receiver1_irq
	wire  [31:0] cpu_d_irq_irq;                                                   // irq_mapper:sender_irq -> cpu:d_irq
	wire         irq_mapper_receiver0_irq;                                        // irq_synchronizer:sender_irq -> irq_mapper:receiver0_irq
	wire   [0:0] irq_synchronizer_receiver_irq;                                   // timer:irq -> irq_synchronizer:receiver_irq
	wire         rst_controller_reset_out_reset;                                  // rst_controller:reset_out -> [cpu:reset_n, irq_mapper:reset, irq_synchronizer:sender_reset, jtag_uart:rst_n, master_clock_crossing_bridge:s0_reset, mm_interconnect_0:cpu_reset_n_reset_bridge_in_reset_reset, pio:reset_n, rst_translator:in_reset, sdram:reset_n]
	wire         rst_controller_reset_out_reset_req;                              // rst_controller:reset_req -> [cpu:reset_req, rst_translator:reset_req_in]
	wire         cpu_jtag_debug_module_reset_reset;                               // cpu:jtag_debug_module_resetrequest -> [rst_controller:reset_in1, rst_controller_001:reset_in1, rst_controller_002:reset_in1]
	wire         rst_controller_001_reset_out_reset;                              // rst_controller_001:reset_out -> [irq_synchronizer:receiver_reset, master_clock_crossing_bridge:m0_reset, mm_interconnect_1:master_clock_crossing_bridge_m0_reset_reset_bridge_in_reset_reset, sysid_qsys_0:reset_n, timer:reset_n]
	wire         rst_controller_002_reset_out_reset;                              // rst_controller_002:reset_out -> [altpll:reset, mm_interconnect_0:altpll_inclk_interface_reset_reset_bridge_in_reset_reset]

	SoC_cpu cpu (
		.clk                                   (altpll_c0_clk),                                       //                       clk.clk
		.reset_n                               (~rst_controller_reset_out_reset),                     //                   reset_n.reset_n
		.reset_req                             (rst_controller_reset_out_reset_req),                  //                          .reset_req
		.d_address                             (cpu_data_master_address),                             //               data_master.address
		.d_byteenable                          (cpu_data_master_byteenable),                          //                          .byteenable
		.d_read                                (cpu_data_master_read),                                //                          .read
		.d_readdata                            (cpu_data_master_readdata),                            //                          .readdata
		.d_waitrequest                         (cpu_data_master_waitrequest),                         //                          .waitrequest
		.d_write                               (cpu_data_master_write),                               //                          .write
		.d_writedata                           (cpu_data_master_writedata),                           //                          .writedata
		.jtag_debug_module_debugaccess_to_roms (cpu_data_master_debugaccess),                         //                          .debugaccess
		.i_address                             (cpu_instruction_master_address),                      //        instruction_master.address
		.i_read                                (cpu_instruction_master_read),                         //                          .read
		.i_readdata                            (cpu_instruction_master_readdata),                     //                          .readdata
		.i_waitrequest                         (cpu_instruction_master_waitrequest),                  //                          .waitrequest
		.d_irq                                 (cpu_d_irq_irq),                                       //                     d_irq.irq
		.jtag_debug_module_resetrequest        (cpu_jtag_debug_module_reset_reset),                   //   jtag_debug_module_reset.reset
		.jtag_debug_module_address             (mm_interconnect_0_cpu_jtag_debug_module_address),     //         jtag_debug_module.address
		.jtag_debug_module_byteenable          (mm_interconnect_0_cpu_jtag_debug_module_byteenable),  //                          .byteenable
		.jtag_debug_module_debugaccess         (mm_interconnect_0_cpu_jtag_debug_module_debugaccess), //                          .debugaccess
		.jtag_debug_module_read                (mm_interconnect_0_cpu_jtag_debug_module_read),        //                          .read
		.jtag_debug_module_readdata            (mm_interconnect_0_cpu_jtag_debug_module_readdata),    //                          .readdata
		.jtag_debug_module_waitrequest         (mm_interconnect_0_cpu_jtag_debug_module_waitrequest), //                          .waitrequest
		.jtag_debug_module_write               (mm_interconnect_0_cpu_jtag_debug_module_write),       //                          .write
		.jtag_debug_module_writedata           (mm_interconnect_0_cpu_jtag_debug_module_writedata),   //                          .writedata
		.no_ci_readra                          ()                                                     // custom_instruction_master.readra
	);

	SoC_sdram sdram (
		.clk            (altpll_c0_clk),                            //   clk.clk
		.reset_n        (~rst_controller_reset_out_reset),          // reset.reset_n
		.az_addr        (mm_interconnect_0_sdram_s1_address),       //    s1.address
		.az_be_n        (~mm_interconnect_0_sdram_s1_byteenable),   //      .byteenable_n
		.az_cs          (mm_interconnect_0_sdram_s1_chipselect),    //      .chipselect
		.az_data        (mm_interconnect_0_sdram_s1_writedata),     //      .writedata
		.az_rd_n        (~mm_interconnect_0_sdram_s1_read),         //      .read_n
		.az_wr_n        (~mm_interconnect_0_sdram_s1_write),        //      .write_n
		.za_data        (mm_interconnect_0_sdram_s1_readdata),      //      .readdata
		.za_valid       (mm_interconnect_0_sdram_s1_readdatavalid), //      .readdatavalid
		.za_waitrequest (mm_interconnect_0_sdram_s1_waitrequest),   //      .waitrequest
		.zs_addr        (sdram_wires_addr),                         //  wire.export
		.zs_ba          (sdram_wires_ba),                           //      .export
		.zs_cas_n       (sdram_wires_cas_n),                        //      .export
		.zs_cke         (sdram_wires_cke),                          //      .export
		.zs_cs_n        (sdram_wires_cs_n),                         //      .export
		.zs_dq          (sdram_wires_dq),                           //      .export
		.zs_dqm         (sdram_wires_dqm),                          //      .export
		.zs_ras_n       (sdram_wires_ras_n),                        //      .export
		.zs_we_n        (sdram_wires_we_n)                          //      .export
	);

	SoC_timer timer (
		.clk        (altpll_c1_clk),                         //   clk.clk
		.reset_n    (~rst_controller_001_reset_out_reset),   // reset.reset_n
		.address    (mm_interconnect_1_timer_s1_address),    //    s1.address
		.writedata  (mm_interconnect_1_timer_s1_writedata),  //      .writedata
		.readdata   (mm_interconnect_1_timer_s1_readdata),   //      .readdata
		.chipselect (mm_interconnect_1_timer_s1_chipselect), //      .chipselect
		.write_n    (~mm_interconnect_1_timer_s1_write),     //      .write_n
		.irq        (irq_synchronizer_receiver_irq)          //   irq.irq
	);

	SoC_sysid_qsys_0 sysid_qsys_0 (
		.clock    (altpll_c1_clk),                                         //           clk.clk
		.reset_n  (~rst_controller_001_reset_out_reset),                   //         reset.reset_n
		.readdata (mm_interconnect_1_sysid_qsys_0_control_slave_readdata), // control_slave.readdata
		.address  (mm_interconnect_1_sysid_qsys_0_control_slave_address)   //              .address
	);

	SoC_pio pio (
		.clk        (altpll_c0_clk),                       //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),     //               reset.reset_n
		.address    (mm_interconnect_0_pio_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio_s1_readdata),   //                    .readdata
		.out_port   (leds_export)                          // external_connection.export
	);

	SoC_altpll altpll (
		.clk       (clk_clk),                                      //       inclk_interface.clk
		.reset     (rst_controller_002_reset_out_reset),           // inclk_interface_reset.reset
		.read      (mm_interconnect_0_altpll_pll_slave_read),      //             pll_slave.read
		.write     (mm_interconnect_0_altpll_pll_slave_write),     //                      .write
		.address   (mm_interconnect_0_altpll_pll_slave_address),   //                      .address
		.readdata  (mm_interconnect_0_altpll_pll_slave_readdata),  //                      .readdata
		.writedata (mm_interconnect_0_altpll_pll_slave_writedata), //                      .writedata
		.c0        (altpll_c0_clk),                                //                    c0.clk
		.c1        (altpll_c1_clk),                                //                    c1.clk
		.c2        (c2_clock_clk),                                 //                    c2.clk
		.areset    (),                                             //        areset_conduit.export
		.locked    (),                                             //        locked_conduit.export
		.phasedone ()                                              //     phasedone_conduit.export
	);

	SoC_jtag_uart jtag_uart (
		.clk            (altpll_c0_clk),                                             //               clk.clk
		.rst_n          (~rst_controller_reset_out_reset),                           //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_jtag_uart_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_jtag_uart_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_jtag_uart_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver1_irq)                                   //               irq.irq
	);

	altera_avalon_mm_clock_crossing_bridge #(
		.DATA_WIDTH          (32),
		.SYMBOL_WIDTH        (8),
		.ADDRESS_WIDTH       (10),
		.BURSTCOUNT_WIDTH    (1),
		.COMMAND_FIFO_DEPTH  (4),
		.RESPONSE_FIFO_DEPTH (4),
		.MASTER_SYNC_DEPTH   (2),
		.SLAVE_SYNC_DEPTH    (2)
	) master_clock_crossing_bridge (
		.m0_clk           (altpll_c1_clk),                                                   //   m0_clk.clk
		.m0_reset         (rst_controller_001_reset_out_reset),                              // m0_reset.reset
		.s0_clk           (altpll_c0_clk),                                                   //   s0_clk.clk
		.s0_reset         (rst_controller_reset_out_reset),                                  // s0_reset.reset
		.s0_waitrequest   (mm_interconnect_0_master_clock_crossing_bridge_s0_waitrequest),   //       s0.waitrequest
		.s0_readdata      (mm_interconnect_0_master_clock_crossing_bridge_s0_readdata),      //         .readdata
		.s0_readdatavalid (mm_interconnect_0_master_clock_crossing_bridge_s0_readdatavalid), //         .readdatavalid
		.s0_burstcount    (mm_interconnect_0_master_clock_crossing_bridge_s0_burstcount),    //         .burstcount
		.s0_writedata     (mm_interconnect_0_master_clock_crossing_bridge_s0_writedata),     //         .writedata
		.s0_address       (mm_interconnect_0_master_clock_crossing_bridge_s0_address),       //         .address
		.s0_write         (mm_interconnect_0_master_clock_crossing_bridge_s0_write),         //         .write
		.s0_read          (mm_interconnect_0_master_clock_crossing_bridge_s0_read),          //         .read
		.s0_byteenable    (mm_interconnect_0_master_clock_crossing_bridge_s0_byteenable),    //         .byteenable
		.s0_debugaccess   (mm_interconnect_0_master_clock_crossing_bridge_s0_debugaccess),   //         .debugaccess
		.m0_waitrequest   (master_clock_crossing_bridge_m0_waitrequest),                     //       m0.waitrequest
		.m0_readdata      (master_clock_crossing_bridge_m0_readdata),                        //         .readdata
		.m0_readdatavalid (master_clock_crossing_bridge_m0_readdatavalid),                   //         .readdatavalid
		.m0_burstcount    (master_clock_crossing_bridge_m0_burstcount),                      //         .burstcount
		.m0_writedata     (master_clock_crossing_bridge_m0_writedata),                       //         .writedata
		.m0_address       (master_clock_crossing_bridge_m0_address),                         //         .address
		.m0_write         (master_clock_crossing_bridge_m0_write),                           //         .write
		.m0_read          (master_clock_crossing_bridge_m0_read),                            //         .read
		.m0_byteenable    (master_clock_crossing_bridge_m0_byteenable),                      //         .byteenable
		.m0_debugaccess   (master_clock_crossing_bridge_m0_debugaccess)                      //         .debugaccess
	);

	SoC_mm_interconnect_0 mm_interconnect_0 (
		.altpll_c0_clk                                            (altpll_c0_clk),                                                   //                                          altpll_c0.clk
		.clock_clk_clk                                            (clk_clk),                                                         //                                          clock_clk.clk
		.altpll_inclk_interface_reset_reset_bridge_in_reset_reset (rst_controller_002_reset_out_reset),                              // altpll_inclk_interface_reset_reset_bridge_in_reset.reset
		.cpu_reset_n_reset_bridge_in_reset_reset                  (rst_controller_reset_out_reset),                                  //                  cpu_reset_n_reset_bridge_in_reset.reset
		.cpu_data_master_address                                  (cpu_data_master_address),                                         //                                    cpu_data_master.address
		.cpu_data_master_waitrequest                              (cpu_data_master_waitrequest),                                     //                                                   .waitrequest
		.cpu_data_master_byteenable                               (cpu_data_master_byteenable),                                      //                                                   .byteenable
		.cpu_data_master_read                                     (cpu_data_master_read),                                            //                                                   .read
		.cpu_data_master_readdata                                 (cpu_data_master_readdata),                                        //                                                   .readdata
		.cpu_data_master_write                                    (cpu_data_master_write),                                           //                                                   .write
		.cpu_data_master_writedata                                (cpu_data_master_writedata),                                       //                                                   .writedata
		.cpu_data_master_debugaccess                              (cpu_data_master_debugaccess),                                     //                                                   .debugaccess
		.cpu_instruction_master_address                           (cpu_instruction_master_address),                                  //                             cpu_instruction_master.address
		.cpu_instruction_master_waitrequest                       (cpu_instruction_master_waitrequest),                              //                                                   .waitrequest
		.cpu_instruction_master_read                              (cpu_instruction_master_read),                                     //                                                   .read
		.cpu_instruction_master_readdata                          (cpu_instruction_master_readdata),                                 //                                                   .readdata
		.altpll_pll_slave_address                                 (mm_interconnect_0_altpll_pll_slave_address),                      //                                   altpll_pll_slave.address
		.altpll_pll_slave_write                                   (mm_interconnect_0_altpll_pll_slave_write),                        //                                                   .write
		.altpll_pll_slave_read                                    (mm_interconnect_0_altpll_pll_slave_read),                         //                                                   .read
		.altpll_pll_slave_readdata                                (mm_interconnect_0_altpll_pll_slave_readdata),                     //                                                   .readdata
		.altpll_pll_slave_writedata                               (mm_interconnect_0_altpll_pll_slave_writedata),                    //                                                   .writedata
		.cpu_jtag_debug_module_address                            (mm_interconnect_0_cpu_jtag_debug_module_address),                 //                              cpu_jtag_debug_module.address
		.cpu_jtag_debug_module_write                              (mm_interconnect_0_cpu_jtag_debug_module_write),                   //                                                   .write
		.cpu_jtag_debug_module_read                               (mm_interconnect_0_cpu_jtag_debug_module_read),                    //                                                   .read
		.cpu_jtag_debug_module_readdata                           (mm_interconnect_0_cpu_jtag_debug_module_readdata),                //                                                   .readdata
		.cpu_jtag_debug_module_writedata                          (mm_interconnect_0_cpu_jtag_debug_module_writedata),               //                                                   .writedata
		.cpu_jtag_debug_module_byteenable                         (mm_interconnect_0_cpu_jtag_debug_module_byteenable),              //                                                   .byteenable
		.cpu_jtag_debug_module_waitrequest                        (mm_interconnect_0_cpu_jtag_debug_module_waitrequest),             //                                                   .waitrequest
		.cpu_jtag_debug_module_debugaccess                        (mm_interconnect_0_cpu_jtag_debug_module_debugaccess),             //                                                   .debugaccess
		.jtag_uart_avalon_jtag_slave_address                      (mm_interconnect_0_jtag_uart_avalon_jtag_slave_address),           //                        jtag_uart_avalon_jtag_slave.address
		.jtag_uart_avalon_jtag_slave_write                        (mm_interconnect_0_jtag_uart_avalon_jtag_slave_write),             //                                                   .write
		.jtag_uart_avalon_jtag_slave_read                         (mm_interconnect_0_jtag_uart_avalon_jtag_slave_read),              //                                                   .read
		.jtag_uart_avalon_jtag_slave_readdata                     (mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata),          //                                                   .readdata
		.jtag_uart_avalon_jtag_slave_writedata                    (mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata),         //                                                   .writedata
		.jtag_uart_avalon_jtag_slave_waitrequest                  (mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest),       //                                                   .waitrequest
		.jtag_uart_avalon_jtag_slave_chipselect                   (mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect),        //                                                   .chipselect
		.master_clock_crossing_bridge_s0_address                  (mm_interconnect_0_master_clock_crossing_bridge_s0_address),       //                    master_clock_crossing_bridge_s0.address
		.master_clock_crossing_bridge_s0_write                    (mm_interconnect_0_master_clock_crossing_bridge_s0_write),         //                                                   .write
		.master_clock_crossing_bridge_s0_read                     (mm_interconnect_0_master_clock_crossing_bridge_s0_read),          //                                                   .read
		.master_clock_crossing_bridge_s0_readdata                 (mm_interconnect_0_master_clock_crossing_bridge_s0_readdata),      //                                                   .readdata
		.master_clock_crossing_bridge_s0_writedata                (mm_interconnect_0_master_clock_crossing_bridge_s0_writedata),     //                                                   .writedata
		.master_clock_crossing_bridge_s0_burstcount               (mm_interconnect_0_master_clock_crossing_bridge_s0_burstcount),    //                                                   .burstcount
		.master_clock_crossing_bridge_s0_byteenable               (mm_interconnect_0_master_clock_crossing_bridge_s0_byteenable),    //                                                   .byteenable
		.master_clock_crossing_bridge_s0_readdatavalid            (mm_interconnect_0_master_clock_crossing_bridge_s0_readdatavalid), //                                                   .readdatavalid
		.master_clock_crossing_bridge_s0_waitrequest              (mm_interconnect_0_master_clock_crossing_bridge_s0_waitrequest),   //                                                   .waitrequest
		.master_clock_crossing_bridge_s0_debugaccess              (mm_interconnect_0_master_clock_crossing_bridge_s0_debugaccess),   //                                                   .debugaccess
		.pio_s1_address                                           (mm_interconnect_0_pio_s1_address),                                //                                             pio_s1.address
		.pio_s1_write                                             (mm_interconnect_0_pio_s1_write),                                  //                                                   .write
		.pio_s1_readdata                                          (mm_interconnect_0_pio_s1_readdata),                               //                                                   .readdata
		.pio_s1_writedata                                         (mm_interconnect_0_pio_s1_writedata),                              //                                                   .writedata
		.pio_s1_chipselect                                        (mm_interconnect_0_pio_s1_chipselect),                             //                                                   .chipselect
		.sdram_s1_address                                         (mm_interconnect_0_sdram_s1_address),                              //                                           sdram_s1.address
		.sdram_s1_write                                           (mm_interconnect_0_sdram_s1_write),                                //                                                   .write
		.sdram_s1_read                                            (mm_interconnect_0_sdram_s1_read),                                 //                                                   .read
		.sdram_s1_readdata                                        (mm_interconnect_0_sdram_s1_readdata),                             //                                                   .readdata
		.sdram_s1_writedata                                       (mm_interconnect_0_sdram_s1_writedata),                            //                                                   .writedata
		.sdram_s1_byteenable                                      (mm_interconnect_0_sdram_s1_byteenable),                           //                                                   .byteenable
		.sdram_s1_readdatavalid                                   (mm_interconnect_0_sdram_s1_readdatavalid),                        //                                                   .readdatavalid
		.sdram_s1_waitrequest                                     (mm_interconnect_0_sdram_s1_waitrequest),                          //                                                   .waitrequest
		.sdram_s1_chipselect                                      (mm_interconnect_0_sdram_s1_chipselect)                            //                                                   .chipselect
	);

	SoC_mm_interconnect_1 mm_interconnect_1 (
		.altpll_c1_clk                                                     (altpll_c1_clk),                                         //                                                   altpll_c1.clk
		.master_clock_crossing_bridge_m0_reset_reset_bridge_in_reset_reset (rst_controller_001_reset_out_reset),                    // master_clock_crossing_bridge_m0_reset_reset_bridge_in_reset.reset
		.master_clock_crossing_bridge_m0_address                           (master_clock_crossing_bridge_m0_address),               //                             master_clock_crossing_bridge_m0.address
		.master_clock_crossing_bridge_m0_waitrequest                       (master_clock_crossing_bridge_m0_waitrequest),           //                                                            .waitrequest
		.master_clock_crossing_bridge_m0_burstcount                        (master_clock_crossing_bridge_m0_burstcount),            //                                                            .burstcount
		.master_clock_crossing_bridge_m0_byteenable                        (master_clock_crossing_bridge_m0_byteenable),            //                                                            .byteenable
		.master_clock_crossing_bridge_m0_read                              (master_clock_crossing_bridge_m0_read),                  //                                                            .read
		.master_clock_crossing_bridge_m0_readdata                          (master_clock_crossing_bridge_m0_readdata),              //                                                            .readdata
		.master_clock_crossing_bridge_m0_readdatavalid                     (master_clock_crossing_bridge_m0_readdatavalid),         //                                                            .readdatavalid
		.master_clock_crossing_bridge_m0_write                             (master_clock_crossing_bridge_m0_write),                 //                                                            .write
		.master_clock_crossing_bridge_m0_writedata                         (master_clock_crossing_bridge_m0_writedata),             //                                                            .writedata
		.master_clock_crossing_bridge_m0_debugaccess                       (master_clock_crossing_bridge_m0_debugaccess),           //                                                            .debugaccess
		.sysid_qsys_0_control_slave_address                                (mm_interconnect_1_sysid_qsys_0_control_slave_address),  //                                  sysid_qsys_0_control_slave.address
		.sysid_qsys_0_control_slave_readdata                               (mm_interconnect_1_sysid_qsys_0_control_slave_readdata), //                                                            .readdata
		.timer_s1_address                                                  (mm_interconnect_1_timer_s1_address),                    //                                                    timer_s1.address
		.timer_s1_write                                                    (mm_interconnect_1_timer_s1_write),                      //                                                            .write
		.timer_s1_readdata                                                 (mm_interconnect_1_timer_s1_readdata),                   //                                                            .readdata
		.timer_s1_writedata                                                (mm_interconnect_1_timer_s1_writedata),                  //                                                            .writedata
		.timer_s1_chipselect                                               (mm_interconnect_1_timer_s1_chipselect)                  //                                                            .chipselect
	);

	SoC_irq_mapper irq_mapper (
		.clk           (altpll_c0_clk),                  //       clk.clk
		.reset         (rst_controller_reset_out_reset), // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),       // receiver0.irq
		.receiver1_irq (irq_mapper_receiver1_irq),       // receiver1.irq
		.sender_irq    (cpu_d_irq_irq)                   //    sender.irq
	);

	altera_irq_clock_crosser #(
		.IRQ_WIDTH (1)
	) irq_synchronizer (
		.receiver_clk   (altpll_c1_clk),                      //       receiver_clk.clk
		.sender_clk     (altpll_c0_clk),                      //         sender_clk.clk
		.receiver_reset (rst_controller_001_reset_out_reset), // receiver_clk_reset.reset
		.sender_reset   (rst_controller_reset_out_reset),     //   sender_clk_reset.reset
		.receiver_irq   (irq_synchronizer_receiver_irq),      //           receiver.irq
		.sender_irq     (irq_mapper_receiver0_irq)            //             sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (2),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.reset_in1      (cpu_jtag_debug_module_reset_reset),  // reset_in1.reset
		.clk            (altpll_c0_clk),                      //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (2),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.reset_in1      (cpu_jtag_debug_module_reset_reset),  // reset_in1.reset
		.clk            (altpll_c1_clk),                      //       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset), // reset_out.reset
		.reset_req      (),                                   // (terminated)
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (2),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_002 (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.reset_in1      (cpu_jtag_debug_module_reset_reset),  // reset_in1.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_002_reset_out_reset), // reset_out.reset
		.reset_req      (),                                   // (terminated)
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

endmodule
